version: "3.3"

services:
  webwat:
    image: node:14
    command: sh -c "yarn install && yarn run dev"
    working_dir: /usr/src/app
    container_name: webwat
    ports:
      - "3001:3000"
    volumes:
      - "./dbdata:/usr/src/app"
    restart: always
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=development
